services:
  db:
    container_name: zoo_animal_management
    image: postgres
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=zoo_animal_management
    volumes:
      - db:/data/postgres
    ports:
      - 5455:5432
    networks:
      - db
    restart: unless-stopped

networks:
  db:
    driver: bridge

volumes:
  db:

