spring:
  datasource:
    url: jdbc:postgresql://localhost:5455/zoo_animal_management
    username: root
    password: root
#    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
  main:
    web-application-type: servlet